### ISSUE TITLE
Create latest release page for 0.28.0

### ISSUE THREAD

**Issue by doveye** [eclipse-openj9/openj9-website#297]
To do:

- [ ] Add OpenJDK support statements (which versions does this release support)
- [ ] Pick one or 2 high value changes from What's new
- [ ] Find out what performance changes should be included
- [ ] Find out if there are any other specific things to highlight for this release
- [ ] Link to the correct version topic in the user doc for more information

See previous issue, #294, for an example.

**Comment by pshipton** [comment]
This was done via https://github.com/eclipse-openj9/openj9-website/pull/301
