### ISSUE TITLE
Xdump and Xtrace Option Builders broken with latest version of Chrome

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse-openj9/openj9-website#306]
It seems that the latest version of Chrome blocks inline javascript.

The source will have to be refactored into separate HTML and javascript files.

**Comment by paulcheeseman** [comment]
Created pull request:
https://github.com/eclipse-openj9/openj9-website/pull/307

**Comment by paulcheeseman** [comment]
Strange. The Option Builder tools have now started working again of their own accord.

The error message I was seeing earlier today looked like this:

> Refused to execute inline event handler because it violates the following Content Security Policy directive: "default-src 'self' *.eclipse.org". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

And none of the javascript code was working at all. But now it's all working fine.

However, inline javascript is generally frowned upon nowadays so I think it's probably a good idea to merge PR #307 anyway to remove it.

**Comment by doveye** [comment]
The PR was merged and things look ok on the live website, so closing this issue.
